spring:
  application:
    name: shared-bike
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari-pool
      connection-timeout: 60000
      minimum-idle: 4
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      generate-ddl: true

  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: ${PORT:8080}

---
spring:
    profiles: dev
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testdb:MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
    h2:
      console:
        enabled: true
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: docker
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/sharedBike?useSSL=false&useUnicode=true&amp;characterEncoding=UTF-8
    username: sharedBike
    password: sharedBike

---
spring:
  profiles: cloud